force-app/main/default/objects/Position__c/fields/Maximum_Pay__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Pay__c</fullName>
    <label>Maximum Pay</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Minimum_Pay__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Pay__c</fullName>
    <label>Minimum Pay</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PositionHandler.cls
public with sharing class PositionHandler {
    public static void autoPopulate(List<Position__c> positionList){
        /** Assignment 32
         * Upon Creation of Position (Custom Object) if it is a New Position and Open Date,Min Pay & Max Pay are not populated then populated with below values:
            a. Open Date = Today’s Date
            b. Min Pay = 10000
            c. Max Pay = 15000.
         */
        if(!positionList.isEmpty()){
            for(Position__c pos : positionList){
                if(pos.Open_Date__c == null && pos.Maximum_Pay__c == null && pos.Minimum_Pay__c == null){
                    pos.Open_Date__c = Date.today();
                    pos.Maximum_Pay__c = 15000;
                    pos.Minimum_Pay__c = 10000;
                }
            }
        }
    }
}